services:
  db:
    image: postgres:16
    container_name: demo_postgres
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: demo_db
      POSTGRES_USER: demo_user
      POSTGRES_PASSWORD: demo_pass
    volumes:
      - demo_pgdata:/var/lib/postgresql/data

volumes:
  demo_pgdata:
